[tool.poetry]
name = "simvue"
version = "0.15.0"
description = "Simulation tracking and monitoring"
authors = ["Simvue Development Team <info@simvue.io>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
GPUtil = "^1.4.0"
py-cpuinfo = "^9.0.0"
dill = "^0.3.7"
requests = "^2.31.0"
msgpack = "^1.0.7"
tenacity = "^8.2.3"
pandas = "^2.1.3"
PyJWT = "^2.8.0"
psutil = "^5.9.6"
pydantic = "1.10.7"
plotly = "^5.18.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[tool.poetry.scripts]
simvue_sender = "simvue.bin.simvue_sender:run"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
