name: Citation File Validation

on:
  push:
    branches: [ "main", "dev", "hotfix/update-ci" ]
  pull_request:
    branches: [ "main", "dev", "hotfix/update-ci" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install Checker
      run: python3 -m pip install cffconvert
    - name: Check Citation File
      run: cffconvert --validate
