name: Simvue Examples

on:
  push:
    branches: [ "main", "dev", "hotfix/update-ci", "296-*" ]
  pull_request:
    branches: [ "main", "dev", "hotfix/update-ci" ]

permissions:
  contents: read

jobs:
  GeometryOptimisation:
    strategy:
        matrix:
            os: ["ubuntu-latest"]
            python-version: ["3.11"]
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/checkout@v4
        - name: Download BlueMira
          uses: actions/checkout@v4
          with:
            repository: Fusion-Power-Plant-Framework/bluemira
            ref: v1.10.0
            path: blue_mira
        - uses: conda-incubator/setup-miniconda@v3
          with:
            activate-environment: bluemira
            environment-file: blue_mira/conda/environment.yml
            miniforge-version: "latest"
            use-only-tar-bz2: false
            miniforge-variant: Mambaforge
            use-mamba: true
            python-version: ${{ matrix.python-version }}
        - name: Install bluemira
          shell: bash -l {0}
          run: pip install -e blue_mira
        - name: Install Simvue
          shell: bash -l {0}
          run: pip install -e .
        - name: Run Example
          shell: bash -l {0}
          run: python ./examples/GeometryOptimisation/bluemira_simvue_geometry_optimisation.py
  Logging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Simvue
        run: python3 -m pip install .
      - name: Run Example
        run: |
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          python3 examples/Logging/logging-to-simvue.py
  OpenFOAM:
    runs-on: ubuntu-latest
    container:
      image: openfoam/openfoam10-paraview56
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Manual Python Install
        run: |
          add-apt-repository ppa:deadsnakes/ppa -y
          apt-get update && \
          apt-get install -y python3.11-full

      - name: Install dependencies
        run: |
          python3.11 -m ensurepip --upgrade
          python3.11 -m pip install ukaea-multiparser
      - name: Install Package
        run: python3.11 -m pip install .
      - name: Run Example
        run: |
          export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
          export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
          python3.11 ./examples/OpenFOAM/simvue_openfoam.py /opt/openfoam10/tutorials/incompressible/pimpleFoam/laminar/movingCone/Allrun
