name: Code Linting

on:
  push:
    branches: [ "main", "dev", "hotfix/update-ci" ]
  pull_request:
    branches: [ "main", "dev", "hotfix/update-ci" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Lint Codebase
      uses: jpetrucciani/ruff-check@0.1.0
      with:
          path: simvue
