name: Simvue Client (Windows)

on:
  push:
    branches: [ "main", "dev", "hotfix/update-ci" ]
  pull_request:
    branches: [ "main", "dev", "hotfix/update-ci" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: python -m pip install poetry
    - name: Test with pytest
      shell: bash
      run: |
        export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
        export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
        poetry install --all-extras
        poetry run pytest tests/unit/ tests/refactor/
