name: Simvue Client (macOS)

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        rm poetry.lock
        python -m pip install poetry
    - name: Test with pytest
      run: |
        export SIMVUE_URL=${{ secrets.SIMVUE_URL }}
        export SIMVUE_TOKEN=${{ secrets.SIMVUE_TOKEN }}
        poetry install --all-extras
        poetry run python -m pip install torch
        poetry run pytest tests/unit/ tests/refactor/ -m 'not scenario'
