name: Simvue Client (Windows)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30
    strategy:
        matrix:
            python-version: ['3.12', '3.13']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: "${{ matrix.python-version }}"
    - name: Install dependencies
      run: |
        rm poetry.lock
        python -m pip install poetry
    - name: Test with pytest
      shell: bash
      run: |
        export SIMVUE_URL=${{ secrets.SIMVUE_NIGHTLY_URL }}
        export SIMVUE_TOKEN=${{ secrets.SIMVUE_NIGHTLY_TOKEN }}
        poetry install --all-extras
        poetry run python -m pip install torch
        poetry run pytest tests/ -m 'not scenario' -m 'not unix'
